### ISSUE TITLE
Send Receipt question

### ISSUE THREAD

**Issue by marcotradenet** [commercionetwork/Commercio-app#1]
I don't understand one thing about the CommerceApp API.

1. Regarding ShareDoc:
   - I have a POST that starts a process that sends me the Doc in Blockchain putting it in a certain queue.
   - I have a GET (on the process ID) to query to figure out when the status of said Doc goes from "enqueued" to something else.
   - At the end of said ambaradan, I get the HASH of my transaction.

2. As for the Receipt:
   - I have a POST similar to the above, but.....
   - ..... I have NOTHING that returns the HASH of the transaction to me once the queuing is complete.
   - I have tried, but there does not appear to be a GET on the Process ID!

I see my `SendReceipt` in Almerico, it's successful, ok, but how do I get the HASH back to the end user from my program????

Thanks

**Comment by ErreVi** [comment]
The POST path for receipts has been updated in dev.commercio.app for testing 
The functionality will be released in production commercio.app with the next deployment
