### ISSUE TITLE
Status not evolving from "Enqueued"

### ISSUE THREAD

**Issue by ndebello** [commercionetwork/Commercio-app#2]
Yesterday I got the log below from GET  /sharedoc/process/ProcessId.

As you can see:

1. it returns "enqueued" forever, no "processing" or "success" as status
2. The response body structure is NOT the one described in the Docs.

I am using chain_id = tesnet10k2,
and URLS starting with "devlogin" and "dev-api".
I also tried the devnet getting the very same results.

Am I wrong somewhere?

=====================================================

The log reports:

1. Status
2. http return code
4. response body

enqueued 200 {"process_id":"023ce249-7587-49af-b5dd-1f0d496f2676","sender":"did:com:1kjsr53jmt52x57g5pd5ma4fsmex43vtrknmrv6","receivers":["did:com:1qu88tsglfxqsjd9l6em9vwvmsasm4tp2pxxwrv"],"document_id":"81b77c4f-b501-4ab1-9625-164119f20fc5","doc_hash":"3cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824","doc_hash_alg":"sha-256","tx_type":"commercionetwork.commercionetwork.documents.MsgShareDocument","doc_storage_uri":"https://dev-api.commercio.app/v1/sharedoc/process","doc_metadata":{"content_uri":"55fa8b74d91bc8443f46b9dc7a179bd3f709bb803f9dccda467310f0fb656a7f","schema":{"uri":"http://example.com/schema.xml","version":"1.0.0"}},"timestamp":"2022-08-03T23:27:21Z","status":"enqueued","back_url":"http://example.com/callback"}

enqueued 200 {"process_id":"023ce249-7587-49af-b5dd-1f0d496f2676","sender":"did:com:1kjsr53jmt52x57g5pd5ma4fsmex43vtrknmrv6","receivers":["did:com:1qu88tsglfxqsjd9l6em9vwvmsasm4tp2pxxwrv"],"document_id":"81b77c4f-b501-4ab1-9625-164119f20fc5","doc_hash":"3cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824","doc_hash_alg":"sha-256","tx_type":"commercionetwork.commercionetwork.documents.MsgShareDocument","doc_storage_uri":"https://dev-api.commercio.app/v1/sharedoc/process","doc_metadata":{"content_uri":"55fa8b74d91bc8443f46b9dc7a179bd3f709bb803f9dccda467310f0fb656a7f","schema":{"uri":"http://example.com/schema.xml","version":"1.0.0"}},"timestamp":"2022-08-03T23:27:21Z","status":"enqueued","back_url":"http://example.com/callback"}

enqueued 200 {"process_id":"023ce249-7587-49af-b5dd-1f0d496f2676","sender":"did:com:1kjsr53jmt52x57g5pd5ma4fsmex43vtrknmrv6","receivers":["did:com:1qu88tsglfxqsjd9l6em9vwvmsasm4tp2pxxwrv"],"document_id":"81b77c4f-b501-4ab1-9625-164119f20fc5","doc_hash":"3cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824","doc_hash_alg":"sha-256","tx_type":"commercionetwork.commercionetwork.documents.MsgShareDocument","doc_storage_uri":"https://dev-api.commercio.app/v1/sharedoc/process","doc_metadata":{"content_uri":"55fa8b74d91bc8443f46b9dc7a179bd3f709bb803f9dccda467310f0fb656a7f","schema":{"uri":"http://example.com/schema.xml","version":"1.0.0"}},"timestamp":"2022-08-03T23:27:21Z","status":"enqueued","back_url":"http://example.com/callback"}

enqueued 200 {"process_id":"023ce249-7587-49af-b5dd-1f0d496f2676","sender":"did:com:1kjsr53jmt52x57g5pd5ma4fsmex43vtrknmrv6","receivers":["did:com:1qu88tsglfxqsjd9l6em9vwvmsasm4tp2pxxwrv"],"document_id":"81b77c4f-b501-4ab1-9625-164119f20fc5","doc_hash":"3cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824","doc_hash_alg":"sha-256","tx_type":"commercionetwork.commercionetwork.documents.MsgShareDocument","doc_storage_uri":"https://dev-api.commercio.app/v1/sharedoc/process","doc_metadata":{"content_uri":"55fa8b74d91bc8443f46b9dc7a179bd3f709bb803f9dccda467310f0fb656a7f","schema":{"uri":"http://example.com/schema.xml","version":"1.0.0"}},"timestamp":"2022-08-03T23:27:21Z","status":"enqueued","back_url":"http://example.com/callback"}

enqueued 200 {"process_id":"023ce249-7587-49af-b5dd-1f0d496f2676","sender":"did:com:1kjsr53jmt52x57g5pd5ma4fsmex43vtrknmrv6","receivers":["did:com:1qu88tsglfxqsjd9l6em9vwvmsasm4tp2pxxwrv"],"document_id":"81b77c4f-b501-4ab1-9625-164119f20fc5","doc_hash":"3cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824","doc_hash_alg":"sha-256","tx_type":"commercionetwork.commercionetwork.documents.MsgShareDocument","doc_storage_uri":"https://dev-api.commercio.app/v1/sharedoc/process","doc_metadata":{"content_uri":"55fa8b74d91bc8443f46b9dc7a179bd3f709bb803f9dccda467310f0fb656a7f","schema":{"uri":"http://example.com/schema.xml","version":"1.0.0"}},"timestamp":"2022-08-03T23:27:21Z","status":"enqueued","back_url":"http://example.com/callback"}

.................

**Comment by ndebello** [comment]
Last week I tried again and -status- was evolving from "enqueued" to "processing", but NOT to "success".
Nonetheless, the transaction now ends correctly (with a returned hash) in the "processing" status.

**Comment by ErreVi** [comment]
The problem has been solved please check the process
