### ISSUE TITLE
Account Configuration Issue after Successfully Login

### ISSUE THREAD

**Issue by GabZan97** [commercionetwork/Commercio-app#4]
I created my account on the mainnet "commercio.app" last year around the 15 dec 2022 and bought a Bronze membership from 15-12-2022 to 15-12-2023
I have been using my account without any issue since ever since.

Since yersteday, I have been receiving this response to my network calls
{"message":"the provided e-identity does not have a valid membership"}

So I tried to login into my account, and after having successfully logged in, I got redirected to https://commercio.app/output-error
Stating that an error has occurred during configuration and to contact administration. 
So I cant verify what is wrong with my account or renew my membership, since I can't access any other menu on my account.

This is the italian message "Si è verificato un errore durante la configurazione, contatta l'amministratore"

My registration email is "complegal.commercio.app@gullivernet.com"

**Comment by ErreVi** [comment]
@GabZan97 Can you try logging back into your account? It seems to be working now. You may have experienced a temporary error due to a platform restart.

**Comment by ErreVi** [comment]
Your membership status is still bronze https://mainnet.commercio.network/account/did:com:1prmw9mz8ujzwcpyed7e7ygs2ek4t55x87ky0dx
